# Generated by Django 4.0.4 on 2022-06-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0004_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='content_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='design_average',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='ratings',
            name='usability_average',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
