# Generated by Django 4.0.4 on 2022-06-17 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myawwards', '0005_ratings_content_average_ratings_design_average_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='loaction',
            new_name='location',
        ),
    ]
